language: node_js
node_js:
  - "6"
git:
  depth: 3
install:
  - npm install
script:
  - npm run lint
branches:
  except:
    - gh-pages
cache:
  directories:
  - $HOME/.npm
  - node_modules
  - example/node_modules
